var emoji = [
    {
      "tts": "woman technologist", 
      "unicode": "U+1F469",
      "files": "👩‍💻",
      "tags": ["person", "female", "woman", "head", "technologist", "computer", "laptop", "work"],
      "author": "Jane Whatever",
      "sentiment": "neutral",    
      "hasSkinTone": "true",
      "hasHairColor": "true",
    },
    {
      "tts": "man swimmer", 
      "unicode": "U+1F3CA",
      "files": "🏊‍♂️",
      "tags": ["swimmer", "swimming", "sports", "person"],
      "author": "George Bell",
      "sentiment": "neutral",    
      "hasSkinTone": "true",
      "hasHairColor": "false",
    },
    {
      "tts": "smiling face with smiling eyes", 
      "unicode": "U+1F60A",
      "files": "😊",
      "tags": ["smile", "happy", "standard", "grinning"],
      "author": "George Bell",
      "sentiment": "happy",    
      "hasSkinTone": "false",
      "hasHairColor": "false",
    },
    {
      "tts": "thumbs up", 
      "unicode": "U+1F44D",
      "files": "👍",
      "tags": ["hand", "positive", "ok", "vote"],
      "author": "George Bell",
      "sentiment": "positive",    
      "hasSkinTone": "true",
      "hasHairColor": "false",
    },
    {
      "tts": "gear", 
      "unicode": "U+2699",
      "files": "⚙️",
      "tags": ["settings", "technical", "hardware", "mechanics"],
      "author": ["George Bell", "Jane Whatever"],
      "sentiment": "positive",    
      "hasSkinTone": "true",
      "hasHairColor": "false",
    },
]

